In [7]:
import sys
print(sys.executable)
print(sys.version)

/opt/conda/envs/anaconda-2025.12-py312/bin/python
3.12.12 | packaged by Anaconda, Inc. | (main, Oct 21 2025, 20:16:04) [GCC 11.2.0]


In [12]:
import sys
!{sys.executable} -m pip install tensorflow

Defaulting to user installation because normal site-packages is not writeable
Looking in links: /usr/share/pip-wheels


In [9]:
%pip install tensorflow

Defaulting to user installation because normal site-packages is not writeable
Looking in links: /usr/share/pip-wheels
Note: you may need to restart the kernel to use updated packages.


In [10]:
import sys
print(sys.executable)
print(sys.version)

/opt/conda/envs/anaconda-2025.12-py312/bin/python
3.12.12 | packaged by Anaconda, Inc. | (main, Oct 21 2025, 20:16:04) [GCC 11.2.0]


In [1]:
import tensorflow
print(tensorflow.__version__)

I0000 00:00:1785270438.525380     533 cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
I0000 00:00:1785270439.711724     533 cpu_feature_guard.cc:227] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
I0000 00:00:1785270443.186022     533 cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.


2.21.0


In [2]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from tensorflow.keras.utils import to_categorical

# Week 6 Day 2 Lab
### Problem 1
Create a neural network with:
- 2 input features
- 8 hidden neurons
- ReLU activation
- 1 sigmoid output neuron


In [9]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
model = Sequential([
    Dense(8, input_shape=(2,), activation="relu"),
    Dense(1, activation="sigmoid")
])
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_2 (Dense)                 │ (None, 8)              │            24 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 1)              │             9 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 33 (132.00 B)

 Trainable params: 33 (132.00 B)

 Non-trainable params: 0 (0.00 B)

### Problem 2
Create your own dataset and train the model for:

- 50 epochs
- 100 epochs
- 300 epochs

Compare the results.


In [12]:
X = np.array([
    [0,0],
    [0,1],
    [1,0],
    [1,1]
], dtype=float)
y =np.array([0,0,0,1])
epochs_list = [50, 100, 300]
for e in epochs_list:
    print(f"\nTraining for {e} epochs")
    model = Sequential([
        Dense(8, input_shape=(2,), activation="relu"),
    Dense(1, activation="sigmoid")
    ])
    model.compile(optimizer="adam",
                loss="binary_crossentropy",
                metrics=["accuracy"])
    model.fit(X,y, epochs=e, verbose=0)
    loss, acc = model.evaluate(X, y, verbose=0)
    print("Loss:", round(loss,4))
    print("Accuracy:", round(acc,4))
    predictions = model.predict(X, verbose=0)
    print("Predictions:")
    print(np.round(predictions,3))


Training for 50 epochs
Loss: 0.6554
Accuracy: 0.75
Predictions:
[[0.474]
 [0.335]
 [0.452]
 [0.379]]

Training for 100 epochs
Loss: 0.6136
Accuracy: 1.0
Predictions:
[[0.451]
 [0.46 ]
 [0.454]
 [0.531]]

Training for 300 epochs
Loss: 0.3848
Accuracy: 1.0
Predictions:
[[0.267]
 [0.336]
 [0.336]
 [0.664]]


### Problem 3

Replace the optimizer:

```python
optimizer="sgd"
```

Compare it with:

```python
optimizer="adam"
```


In [13]:
#optimizer='sgd'
model_sgd = Sequential([
    Dense(8, input_shape=(2,), activation="relu"),
    Dense(1, activation="sigmoid")
])
model_sgd.compile(
    optimizer="sgd",
    loss="binary_crossentropy",
    metrics=["accuracy"]
)
model_sgd.fit(X, y, epochs=100, verbose=0)
loss_sgd, acc_sgd = model_sgd.evaluate(X, y, verbose=0)
print("SGD Accuracy:", acc_sgd)

SGD Accuracy: 0.75


In [14]:
#optimizer="adam"
model_adam = Sequential([
    Dense(8, input_shape=(2,), activation="relu"),
    Dense(1, activation="sigmoid")
])
model_adam.compile(
    optimizer="adam",
    loss="binary_crossentropy",
    metrics=["accuracy"]
)
model_adam.fit(X, y, epochs=100, verbose=0)
loss_adam, acc_adam = model_adam.evaluate(X, y, verbose=0)
print("Adam Accuracy:", acc_adam)

Adam Accuracy: 0.75


### Problem 4
Create a neural network for the Iris dataset using:

- Input layer
- One hidden layer
- Three output neurons
- Softmax activation